/* config.h -- hand-written for sxbv's vendored, stripped Poppler core.
 *
 * Originally generated by CMake from config.h.cmake. sxbv builds Poppler's
 * core as a plain Makefile-driven static library with no CMake involved,
 * so this file is maintained by hand. Keep it in sync with config.h.cmake
 * if Poppler's source is ever re-vendored from a newer upstream snapshot.
 */

#ifndef SXBV_POPPLER_CONFIG_H
#define SXBV_POPPLER_CONFIG_H

#include "poppler-config.h"

/* Build against libcurl -- OFF. sxbv only opens local files; no networked
 * PDF fetching, so libcurl (and its TLS/Kerberos/LDAP transitive deps)
 * is dropped entirely. */
#define ENABLE_LIBCURL 0

/* Build with libopenjpeg support -- ON. Needed to decode JPEG2000 images
 * embedded in PDFs (a real, if uncommon, feature). openjpeg is small and
 * dependency-free, so there's no reason to cut it. */
#define ENABLE_LIBOPENJPEG 1

/* Do not hardcode the library location -- irrelevant for a static lib
 * linked into a single binary. */
#define ENABLE_RELOCATABLE 0

/* Digital signature backends -- both OFF. sxbv never validates or creates
 * signatures, so neither NSS3 nor GPGME (and their dependency trees) are
 * linked in. The Form/CryptoSignBackend code paths that reference these
 * still compile -- Factory::create() just returns nullptr for every
 * backend type, which is what we want. */
#define ENABLE_NSS3 0
#define ENABLE_GPGME 0
#define ENABLE_PGP_SIGNATURES 0

/* Signature *types* (SignatureInfo, CryptoSignBackend, Form's signature
 * fields) still need to exist as real compiled code -- Form.cc, Page.cc,
 * Catalog.cc reference them unconditionally during normal page loading,
 * not just when a document actually contains a signature. With both
 * backends above set to 0, validateSignatureAsync() etc. simply have no
 * backend to call into and fail gracefully; sxbv never invokes them. */
#define ENABLE_SIGNATURES 1

#define DEFAULT_SIGNATURE_BACKEND ""

/* Platform feature probes -- accurate for a modern Linux/glibc target. */
#define HAVE_FSEEK64 0
#define HAVE_FSEEKO 1
#define HAVE_PREAD64 1
#define HAVE_LSEEK64 1
#define HAVE_GMTIME_R 1
#define HAVE_TIMEGM 1
#define HAVE_LOCALTIME_R 1
#define HAVE_STRTOK_R 1

#define WORDS_BIGENDIAN 0

#define ICONV_CONST

#define PACKAGE "poppler"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_NAME "poppler"
#define PACKAGE_STRING "poppler 26.06.90 (sxbv-vendored, stripped)"
#define PACKAGE_TARNAME "poppler"
#define PACKAGE_URL ""
#define PACKAGE_VERSION "26.06.90"

#define POPPLER_DATADIR ""

#define VERSION "26.06.90"

/* Font configuration backend -- fontconfig, matching sxbv.h's existing
 * X11/Xft usage. */
#define WITH_FONTCONFIGURATION_FONTCONFIG 1
#define WITH_FONTCONFIGURATION_WIN32 0
#define WITH_FONTCONFIGURATION_ANDROID 0

#endif /* SXBV_POPPLER_CONFIG_H */
